### ISSUE TITLE
Отображение графиков и поддержка автоматизаций в умном доме 

### ISSUE THREAD

**Issue by pervolianinen** [dext0r/yandex_smart_home#391]
В текущей версии приложения от Яндекс реализована поддержка отображения графиков состояния датчиков (устройств) и создание сценариев для датчиков.
Загружаемые из Home Assistent датчики в данных сценариях и автоматизациях не поддерживаются.
При это те же самые устройства и датчики (tuya, aqara) поддерживаются при подключении не через Home assistent.

**Comment by dext0r** [comment]
Несколько вопросов:
1. Какие конкретно датчики не поддерживаются в сценариях?
2. По этим датчикам отображаются графики в приложении Дом с Алисой?

**Comment by pervolianinen** [comment]
> Несколько вопросов:
> 
> 1. Какие конкретно датчики не поддерживаются в сценариях?

Никакие датчики и устройства (подгружаемые из home assistent), как условия сценария (не действие) не поддерживаются

> 2. По этим датчикам отображаются графики в приложении Дом с Алисой?

По датчикам и устройствам из home assistent графики не отображаются. "Производитель не поддерживает историю показаний датчика". 
Это например для Яндекс розетки подключенной через ha.

**Comment by dext0r** [comment]
У вас прямое подключение? Скорее всего не настроена отправка уведомлений об изменении состояний устройств ([подробнее в документации](https://github.com/dmitry-k/yandex_smart_home/blob/master/docs/direct-connection.md#%D1%83%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BE%D0%B1-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B8-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B9-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2)). Нужно её настроить, затем обновить список устройств в УДЯ.

**Comment by varakirill** [comment]
У меня датчики температуры/владжности aqara прокинуты в УДЯ из НА - в УДЯ есть по ним графики и дает использовать в сценариях.

**Comment by dext0r** [comment]
Вы не ответили на вопрос: у вас компонент Yandex Smart Home использует прямое подключение или облачное?

> У меня датчики температуры/влажности aqara прокинуты в УДЯ из НА - в УДЯ есть по ним графики и дает использовать в сценариях.

Но выше вы сказали "По датчикам и устройствам из home assistent графики не отображаются"

**Comment by varakirill** [comment]
> Вы не ответили на вопрос: у вас компонент Yandex Smart Home использует прямое подключение или облачное?
> 
> > У меня датчики температуры/влажности aqara прокинуты в УДЯ из НА - в УДЯ есть по ним графики и дает использовать в сценариях.
> 
> Но выше вы сказали "По датчикам и устройствам из home assistent графики не отображаются"
> 

Я лишь сообщил что у меня все работает корректно, в отличии от автора. И напрямую и через облако.

**Comment by dext0r** [comment]
> > Вы не ответили на вопрос: у вас компонент Yandex Smart Home использует прямое подключение или облачное?
> > > У меня датчики температуры/влажности aqara прокинуты в УДЯ из НА - в УДЯ есть по ним графики и дает использовать в сценариях.
> > 
> > 
> > Но выше вы сказали "По датчикам и устройствам из home assistent графики не отображаются"
> 
> Я лишь сообщил что у меня все работает корректно, в отличии от автора. И напрямую и через облако.

Извиняюсь, не увидел, что отвечает не автор 😓

**Comment by pervolianinen** [comment]
> у вас компонент Yandex Smart Home использует прямое подключение

Прямое.

**Comment by dext0r** [comment]
> Прямое.

Настройте отправку уведомлений об изменении состояний устройств ([подробнее в документации](https://github.com/dmitry-k/yandex_smart_home/blob/master/docs/direct-connection.md#%D1%83%D0%B2%D0%B5%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BE%D0%B1-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B8-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B9-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2)). После этого обновите список устройств в УДЯ.
