### ISSUE TITLE
Не обновляется состояние MI Desk Lamp 1S MJTD01SYL

### ISSUE THREAD

**Issue by DrSchmurge** [dext0r/yandex_smart_home#392]
Имею две настольные лампы MJTD01SYL, подключены в HA через Homekit Controller.
Управляются через яндекс корректно, состояние после включения\отключения через яндекс отображается норм.
Но если включить лампу кнопкой на ней самой или любой автоматизацией, то яндекс не получает смену состояния (то есть я лампу включил, а в яндексе она числится выключенной).
С остальными 20+ приборами (все Zigbee2mqtt) такой проблемы не замечаю.

HA 2022.5.2
Yandex Smart Home v0.5.1

**Comment by dext0r** [comment]
> Но если включить лампу кнопкой на ней самой или любой автоматизацией, то яндекс не получает смену состояния (то есть я лампу включил, а в яндексе она числится выключенной).

А в HA она при этом меняет своё состояние?
Если зайти в лампу в УДЯ, в журнале HA появится ошибка `State requested for unexposed entity`?

> Yandex Smart Home v0.5.1

Используется подключение через облако (Yaha Cloud) или прямое (через свой навык)?

**Comment by DrSchmurge** [comment]
> > Но если включить лампу кнопкой на ней самой или любой автоматизацией, то яндекс не получает смену состояния (то есть я лампу включил, а в яндексе она числится выключенной).
> 
> А в HA она при этом меняет своё состояние? Если зайти в лампу в УДЯ, в журнале HA появится ошибка `State requested for unexposed entity`?
> 
> > Yandex Smart Home v0.5.1
> 
> Используется подключение через облако (Yaha Cloud) или прямое (через свой навык)?

Да, в том и дело что в HA состояние меняется.
В журнале не появляется ничего, правда уровень логов у меня error, какого уровня это сообщение должно быть? Опущу логи до debug, гляну что происходит.
Использую через Yaha Cloud

**Comment by DrSchmurge** [comment]
> > В журнале не появляется ничего, правда уровень логов у меня error, какого уровня это сообщение должно быть?
> 
> Это Warning. И появляется он только при входе в устройство в УДЯ.
> 
> > Использую через Yaha Cloud
> 
> Проблемное устройство выбрано для передачи в УДЯ в настройках интеграции или через блок `filter` в YAML? Очень похоже, что нет. Но в этом случае должен возникает warning при входе в устройство в УДЯ.

Да, выбрано в GUI в настройках интеграции, для надежности удалил его ооттуда -> рефрешнул устройства через яндекс -> добавил обратно, ничего не изменилось
в логах увидел много соответствующих warning : State requested for unexposed entity ... , но по этим лампам их нет
Плюс они же управляются корректно из яндекса, значит они проброшены, но связь почему-то односторонняя
![image](https://user-images.githubusercontent.com/58488420/172365362-3aeb234f-8442-43d5-9669-034100801a12.png)

**Comment by dext0r** [comment]
> Плюс они же управляются корректно из яндекса, значит они проброшены, но связь почему-то односторонняя

После добавления устройства в УДЯ, его можно удалить оттуда только вручную. И удаление его из списка передаваемых устройств никак не повлияет на возможность управлять им (но будут варнинги).

> Это единственные девайсы, которые заведены в HA через HomeKit, может ли быть с этим связано?
Или если в HA корректно меняется их состояние, то оно должно пробрасываться в YAHA вне зависимости от того, через какую интеграцию первоначально добавлен девайс?

Вряд ли это как-то связано, но возможно разное :)

Давайте попробуем:
1. Включите дебаг для yandex_smart_home и перезагрузите HA:
```logger:
  default: warning
  logs:
    custom_components.yandex_smart_home: debug
```
2. Выполните обновления списка устройств в УДЯ, в логе homeassistant.log будут строки:
```
 [custom_components.yandex_smart_home.cloud] Request: /user/devices (message: {})
 [custom_components.yandex_smart_home.cloud] Response: МНОГО_БУКВ
```
3. Убедитесь, что в Response есть проблемная лампа (искать по entity_id)
4. Если в лампа в Response есть - помигайте ей через HA с задержкой в 2 секунды
5. Проверьте, появились ли в логе строчки вида:
```
[custom_components.yandex_smart_home.notifier] Scheduling report state to Yandex for light.ИД_ЛАМПЫ: on
[custom_components.yandex_smart_home.notifier] Request: https://yaha-cloud.ru/api/home_assistant/v1/callback/state (POST data: {"ts": 1654607385.5576987, "payload": {"devices": [{"properties": [], "capabilities": [{"type": "devices.capabilities.on_off", "state": {"instance": "on", "value": true}}], "id": "light.ИД_ЛАМПЫ"}], "user_id": "неважно"}})
```
