### ISSUE TITLE
Нет поддержки устройств типа sensor.  и binary_sensor.

### ISSUE THREAD

**Issue by byOZN** [dext0r/yandex_smart_home#394]
Суть проблемы такова:
Использую плк для сбора телеметрии и управления светом , передача данных у меня устроена так :
Температура ->STM32 -> MODBUS_RTU-> ПЛК -> MODBUS_TCP -> HA -> sensor.temp
Так вот , при передачи этого параметра в YAHA он не определяет что добавлено новое устройство
То же самое и с выключателями :
Физический выключатель -> INPUT ПЛК -> MODBUS_TCP -> HA -> binary_sensor.inputPLC
В бинарный сенсор можно добавить много чего полезного , я решил его использовать как состояние выключателя.
Устройства типа бинарный сенсор не добавляется в YAHA , а если делать его типа switch то в YAHA он определяется не очень корректно "выключатель с возможностью его переключения" и невозможностью использования его в атоматизации в Дом с алисой , как условие для тригера.

**Comment by byOZN** [comment]
> > Температура ->STM32 -> MODBUS_RTU-> ПЛК -> MODBUS_TCP -> HA -> sensor.temp
> > Так вот , при передачи этого параметра в YAHA он не определяет что добавлено новое устройство
> 
> Скорее всего у `sensor.temp` не заданы `device_class: temperature` и `unit_of_measurement: °C`
> 
Да , действительно , добавил device_class: temperature и все  автоматом подтянулось , а где бы посмотреть список поддерживаемых device_class в YAHA
> > Устройства типа бинарный сенсор не добавляется в YAHA , а если делать его типа switch то в YAHA он определяется не очень корректно "выключатель с возможностью его переключения"
> 
> Нужно делать switch, УДЯ не умеет "переключатели, которые не могут переключаться"
> 
Да , но как же быть с бинарными сенсорами , штука же очень полезная ?? например "концевик" открытия двери. 
> > и невозможностью использования его в атоматизации в Дом с алисой , как условие для тригера.
> 
> У вас прямое подключение? Скорее всего не настроена отправка уведомлений об изменении состояний устройств 
>
подключение облачное

**Comment by dext0r** [comment]
> Да , действительно , добавил device_class: temperature и все автоматом подтянулось, а где бы посмотреть список поддерживаемых device_class в YAHA

На данный момент такого списка нет. Добавлю в документацию, сейчас как раз занимаюсь её доработкой и изменением структуры.

> Да , но как же быть с бинарными сенсорами , штука же очень полезная ?? например "концевик" открытия двери.

Это зависит от сенсора. Например, с 0.5.1 для всех стали доступные бинарные датчики, в том числе открытия двери (`device_class: door, garage_door, window, opening`). Все бинарные датчики, которые умеет УДЯ, смотрите [тут](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/event-instance.html). Возможные `device_class` в HA - [тут](https://www.home-assistant.io/integrations/binary_sensor/#device-class) и [тут](https://www.home-assistant.io/integrations/sensor/#device-class).

> подключение облачное

Похоже УДЯ на данный момент умеет запускать сценарии только по сенсорам :(
