### ISSUE TITLE
Висит браузер при удалении устройства

### ISSUE THREAD

**Issue by de-salvatierra** [dext0r/yandex_smart_home#400]
При удалении устройства зависает браузер на несколько секунд (доходило до минуты), после этого отвисает и устройство удаляется.
Мне нужно удалить кучу устройств. на это уйдет весь день и все нервы)
Это только у меня так или ошибка глобальная?
Браузер Google Chrome
HA через днс от кинетика
![image](https://user-images.githubusercontent.com/5816848/176763930-c8431d7e-dae1-46ac-a5f7-2a2d61cefdca.png)

**Comment by dext0r** [comment]
Не могу воспроизвести проблему у себя. Создал 300 устройств, попробовал поудалять некоторые - всё быстро. 

У вас проблема на десктопе или планшете? Какая версия HA? Можно попробовать через Firefox.


https://user-images.githubusercontent.com/3103856/176848519-3289d428-0ea5-40b3-95a3-fc9f994a26ba.mov
