### ISSUE TITLE
Интеграция 4-хканального реле

### ISSUE THREAD

**Issue by booroondookZ** [dext0r/yandex_smart_home#402]
В Home Assistant'е имеется 4-хканальное реле, управляющее вытяжкой над кухонной плитой (каждый канал включает разные скорости вентилятора). Основа реле - ESP8266 (точнее - ESP-12F). Плюс еще имеется датчик температуры DS18B20, также подключенный к одному из GPIO этого реле. Прошивка - Tasmota.
На текущий момент у меня каждый канал и датчик температуры добавляется как отдельное устройство - то есть, всего 5 устройств.
Вопрос - как добавить это реле в Yandex Smart Home как единое устройство с 4 выключателями и датчиком температуры?

**Comment by dext0r** [comment]
К сожалению, никак. УДЯ поддерживает только один выключатель на одно устройство.

**Comment by booroondookZ** [comment]
Да, приходится признать "недоделанность" Яндекса. Причем, не только по отношению к Home Assistant, но и вообще.
Например, похожее 4-хканальное реле из интеграции eWelink преобразуется в 5 (пять!!!) не связанных друг с другом устройств - по одному на каждый канал, да плюс еще некий "общий" выключатель, который одновременно включает или выключает все четыре канала сразу.
И та же беда с Tuya - двухканальный выключатель превращается в три отдельных устройства - точно так же, как с реле: на каждый канал своё устройство плюс "общее".
