### ISSUE TITLE
Расширить features в entity_config

### ISSUE THREAD

**Issue by dext0r** [dext0r/yandex_smart_home#405]
Добавить play_pause и возможно другие. Кейс: universal mediaplayer с children. 
Дополнительно подумать о кешировании features (3508 когда ТВ выключен, 155581 при включенном).

см. https://t.me/yandex_smart_home/31853

**Comment by Drafteed** [comment]
Интересную особенность увидел. Похоже `universal` когда все `childs` выключены не отдает реальный список фич.

Вот например интеграция LG Netcast:

Выключенный оригинал: `supported_features: 20413`
Эта же сущность через universal, [команды on/off в оверайде](https://gist.github.com/Drafteed/bb4e1f52f2663dca7fcd8dfd46e53232): `supported_features: 384`

Благодаря этому, УДЯ также успешно теряет навык каналов при обновлении с выключенным ТВ.

Ох уж эти медиа-плееры в ХА...

**Comment by Drafteed** [comment]
> https://github.com/dext0r/yandex_smart_home/commit/27df1e54cc255c313f2cd9e15e36c58472e947d2

Эх, еще бы `play_media` добавить, так как:

> Благодаря этому, УДЯ также успешно теряет навык каналов (да и другие тоже) при обновлении с выключенным ТВ.

**Comment by Drafteed** [comment]
Вообще, я бы этот список `features` превратил бы в `dict[str, bool]` чтобы можно было явно включать или принудительно выключать навык. Тогда, можно было бы избавиться от отдельной крутилки `support_set_channel`.

**Comment by dext0r** [comment]
> Эх, еще бы play_media добавить, так как:

Да, действительно нужен, добавил.

> Вообще, я бы этот список features превратил бы в dict[str, bool] чтобы можно было явно включать или принудительно выключать навык. Тогда, можно было бы избавиться от отдельной крутилки support_set_channel, которая его только принудительно выключает.

Я всё ещё надеюсь на большие изменения в ядре HA для медиаплееров, потому что сейчас это очень похоже на кучу костылей, которую вряд ли получится адекватно сделать :) А от `support_set_channel` не получится отказаться, он управляет поведением +/- для каналов.
