### ISSUE TITLE
Не передается CO2 в Алису

### ISSUE THREAD

**Issue by iljasorokin** [dext0r/yandex_smart_home#408]
Пытаюсь пробросить в Алису датчик CO2  из интеграции Xiaomi Miot Auto https://github.com/al-one/hass-xiaomi-miot  (Qingping Air Monitor Lite CGDN1)

![image](https://user-images.githubusercontent.com/34852547/184079661-07052a0c-7db0-4b79-bf4a-271a99d24332.png)

В Home Assistant выглядит все норм:

![image](https://user-images.githubusercontent.com/34852547/184079929-f26a7ac3-e646-493c-b7cd-137920104d80.png)

В Алисе у этого датчика появляется только уровень зарядки. Это проблема [yandex_smart_home](https://github.com/dext0r/yandex_smart_home) или искать в других компонентах?

**Comment by dext0r** [comment]
> Это проблема [yandex_smart_home](https://github.com/dext0r/yandex_smart_home) или искать в других компонентах?

Покажите все атрибуты у сенсора из панели разработчика. Скорее всего у него отсутствует атрибут `device_class: carbon_dioxide`

**Comment by iljasorokin** [comment]
> > Это проблема [yandex_smart_home](https://github.com/dext0r/yandex_smart_home) или искать в других компонентах?
> 
> Покажите все атрибуты у сенсора из панели разработчика. Скорее всего у него отсутствует атрибут `device_class: carbon_dioxide`

Спасибо!

Все получилось. Добавил поле device_class:

`homeassistant:
  customize:
    sensor.bedroom_co2_density:
        device_class: carbon_dioxide`

Спасибо за шикарную инструкцию по составным датчикам, собрал все в одном просто через атрибуты 

`        sensor.kids_env_environment:
          name: Воздух в детской
          properties:
            - type: temperature
              attribute: environment.temperature
            - type: humidity
              attribute: environment.relative_humidity
            - type: co2_level
              attribute: environment.co2_density
            - type: pm10_density
              attribute: environment.pm10_density
            - type: pm2.5_density
              attribute: environment.pm2_5_density   `
