### ISSUE TITLE
Кнопки цветов лампочки не соответствуют действительности

### ISSUE THREAD

**Issue by whakru** [dext0r/yandex_smart_home#412]
![Screenshot_2022-08-30-10-48-05-218_com yandex iot](https://user-images.githubusercontent.com/22603145/187380481-95e86388-72c5-407e-8a91-7379d6d2bcbe.jpg)
Если посмотреть на пресеты. То желтый допустим это больше оранжевый. И по факту выходит так же.
Вот например выбран цвет в Яндексе жёлтый. И палитра в ha:
![Screenshot_2022-08-30-10-29-56-163_io homeassistant companion android](https://user-images.githubusercontent.com/22603145/187380776-76302dd5-73d9-4607-9f1b-8d89ab7789d7.jpg)
Видно что по палитре это далеко не жёлтый.

Это как то можно пофиксить?

**Comment by dext0r** [comment]
> Это как то можно пофиксить?

https://docs.yaha-cloud.ru/v0.6.x/devices/light/
