### ISSUE TITLE
Unsupported HA mode "on" for fan_speed

### ISSUE THREAD

**Issue by DieMetRik** [dext0r/yandex_smart_home#413]
Эта ошибка возникла в кастомной интеграции.

```
Logger: homeassistant
Source: custom_components/yandex_smart_home/capability_mode.py:106
Integration: Yandex Smart Home (documentation, issues)
First occurred: 15 сентября 2022 г., 19:27:10 (9 occurrences)
Last logged: 08:34:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 288, in _state_change_listener
    await asyncio.gather(*[n.async_event_handler(event) for n in hass.data[DOMAIN][NOTIFIERS]])
  File "/config/custom_components/yandex_smart_home/notifier.py", line 203, in async_event_handler
    callback_state.old_state = YandexEntityCallbackState(
  File "/config/custom_components/yandex_smart_home/entity.py", line 269, in __init__
    state = item.get_state()
  File "/config/custom_components/yandex_smart_home/capability.py", line 62, in get_state
    value = self.get_value()
  File "/config/custom_components/yandex_smart_home/capability_mode.py", line 142, in get_value
    return self.get_yandex_mode_by_ha_mode(ha_mode, False)
  File "/config/custom_components/yandex_smart_home/capability_mode.py", line 106, in get_yandex_mode_by_ha_mode
    raise SmartHomeError(ERR_INVALID_VALUE, err)
custom_components.yandex_smart_home.error.SmartHomeError: Unsupported HA mode "on" for fan_speed instance of climate.rclima_bedroom. Maybe it missing in entity attribute fan_modes?
```

Добрый день! Возникла такая проблема.
Кондиционер подключён через ESPHome и platform: midea
ESP автоматом определяет все возможные режимы работы кондиционера.
Но вот режима ON для FAN_SPEED нет.

Как то можно поправить это?

Кондиционер через Алису управляется и меняется температура и режимы работы. Но вот эта ошибка возникает все равно.
Все версии программ последние доступные.

**Comment by dext0r** [comment]
Покажите атрибуты этого кондиционера из Панель разработчика -> Состояния

**Comment by DieMetRik** [comment]
![image](https://user-images.githubusercontent.com/31734768/193815888-678d467e-1dc9-4497-8c2d-e2ba6a57de16.png)

**Comment by dext0r** [comment]
Я посмотрел код esphome и не смог найти условия при которых `fan_mode` может стать `on`. При каких условиях возникает ошибка? Возможно ли воспроизвести ситуацию, когда в атрибутах будет `fan_mode: on`?

**Comment by DieMetRik** [comment]
Если я правильно понял, Яндекс запрашивает этот статус у home assistant. Но его нет в entity

**Comment by DieMetRik** [comment]
Пытаюсь хоть как то воспроизвести эту ошибку. Но пока не могу уловить взаимосвязь
