### ISSUE TITLE
Не удалось обновить список устройств

### ISSUE THREAD

**Issue by zhvial** [dext0r/yandex_smart_home#415]
При добавлении rgbw контроллера Zigbee TS0504B перестает обновляться список устройств в приложении удя. В HA логах вылетает ошибка:

Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/capability_color.py:498
Integration: Yandex Smart Home (documentation, issues)
First occurred: 17:11:50 (15 occurrences)
Last logged: 17:43:42

Handler unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 37, in async_handle_message
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 79, in async_devices
    serialized = await entity.devices_serialize(ent_reg, dev_reg, area_reg)
  File "/config/custom_components/yandex_smart_home/entity.py", line 165, in devices_serialize
    for item in [c.description() for c in self.capabilities()]:
  File "/config/custom_components/yandex_smart_home/entity.py", line 165, in <listcomp>
    for item in [c.description() for c in self.capabilities()]:
  File "/config/custom_components/yandex_smart_home/capability.py", line 54, in description
    parameters = self.parameters()
  File "/config/custom_components/yandex_smart_home/capability_color.py", line 96, in parameters
    min_temp, max_temp = self._temperature_converter.supported_temperature_range
  File "/config/custom_components/yandex_smart_home/capability_color.py", line 209, in _temperature_converter
    return TemperatureConverter(color_profile, self.state)
  File "/config/custom_components/yandex_smart_home/capability_color.py", line 498, in __init__
    if min_temp + range_extend_threshold < min(self._ha_value_to_yandex):
ValueError: min() arg is an empty sequence

Если устройство не передавать в удя, все работает.

**Comment by dext0r** [comment]
Покажите список атрибутов для этого устройства из панели разработчика.

**Comment by zhvial** [comment]
![Screenshot_20221002-195338_Home Assistant](https://user-images.githubusercontent.com/60042073/193466281-0ce3ae39-e684-4fec-ab75-abfe1e9c0b56.jpg)

Этого достаточно ?

**Comment by zhvial** [comment]
https://www.zigbee2mqtt.io/devices/TS0504B.html#tuya-ts0504b

**Comment by zhvial** [comment]
https://www.zigbee2mqtt.io/devices/TS0504B.html#tuya-ts0504b

**Comment by dext0r** [comment]
> Этого достаточно ?

Да, ошибка будет исправлена в следующем релизе. Возникает из-за "странного" диапазона цветовых температур (2000К-2008К)

**Comment by zhvial** [comment]
Спасибо. И за плагин спасибо!
Ещё, я считаю, что ошибки должны как то по другому обрабатываться. Не должно быть так, что из-за одного устройства полностью перестает обновляться список. 
Я это устройство нашел поочередно добавляя каждый источник света. А до этого пол дня не мог понять почему через include_domains light ничего не работает.

**Comment by dext0r** [comment]
Исправление войдёт в следующий релиз, пока можно поставить версию из мастера.

> Ещё, я считаю, что ошибки должны как то по другому обрабатываться. Не должно быть так, что из-за одного устройства полностью перестает обновляться список.

Ошибки конфигурации обрабатывается по другому (в логе будет указание конкретного устройства и что с ним не так). Эта же ошибка компонента, поэтому дополнительно никак ловиться не должна.
