### ISSUE TITLE
Не работает media_player.philips_tv в УДЯ

### ISSUE THREAD

**Issue by salex105** [dext0r/yandex_smart_home#419]
есть такая интеграция
https://www.home-assistant.io/integrations/philips_js/

из самого HA работает, переключаются канал, видно список каналов с названиями.

а если прокинуть это устройство media_player.philips_tv в УДЯ
то не работает переключение каналов. работает mute и регулировка звука, при чем некорректно. например в пульте УДЯ значение звука 30, на тв 18.
так же список источников в HA видно корректно по названиям, в УДЯ оно работает, но список там: Один, Два и тп

что можно сделать? какие данные вам прислать?

**Comment by dext0r** [comment]
> то не работает переключение каналов. 

В каком смысле "Не работает"? Неактивен выбор канала в УДЯ или при выборе канала ничего не происходит?

> при чем некорректно. например в пульте УДЯ значение звука 30, на тв 18.

Панель разработчика -> Службы -> `media_player.volume_set`. При изменении громкости через этот сервис она корректно изменяется на телевизоре?

> но список там: Один, Два и тп

УДЯ по-другому не умеет.

Дополнительный вопрос: подключение прямое или облачное? Если прямое - настроен нотификатор? (https://docs.yaha-cloud.ru/v0.6.x/advanced/direct-connection/#notifier)

**Comment by salex105** [comment]
> В каком смысле "Не работает"? Неактивен выбор канала в УДЯ или при выборе канала ничего не происходит?

выбор активен, но при выборе канала, или перелистывании каналов вверх-вниз, ничего не происходит



> Панель разработчика -> Службы -> `media_player.volume_set`. При изменении громкости через этот сервис она корректно изменяется на телевизоре?

Что нужно добавить там? если просто вызвать вызвать `media_player.volume_set`, то ответ такой:
Не удалось вызвать службу media_player.volume_set. required key not provided @ data['volume_level']. Got None



> Дополнительный вопрос: подключение прямое или облачное? Если прямое - настроен нотификатор? (https://docs.yaha-cloud.ru/v0.6.x/advanced/direct-connection/#notifier)

судя по всему, подключение прямое. про нотификатор сейчас почитаю

**Comment by dext0r** [comment]
> Что нужно добавить там? если просто вызвать вызвать media_player.volume_set, то ответ такой:
> Не удалось вызвать службу media_player.volume_set. required key not provided @ data['volume_level']. Got None

Желаемую громкость (параметр `volume_level`).

> Еще обратил внимание, что можно управлять через т.н. пульт: remote.send_command
> есть возможность привязать в УДЯ media_player кнопки к remote.send_command?

Средствами компонента это будет сделать затруднительно. Можно попробовать создать медиаплеер на шаблоне, в котором запрограммировать желаемое поведение - https://www.home-assistant.io/integrations/universal/

> выбор активен, но при выборе канала, или перелистывании каналов вверх-вниз, ничего не происходит

Давайте попробуем следующее:
1. Включите дебаг компонента (https://docs.yaha-cloud.ru/v0.6.x/troubleshoot/debug/#logger)
2. **Выключите телевизор**
3. Перезапустите HA
4. Сразу после перезапуска сделайте скриншот атрибутов телевизора из Панель разработчика - Состояния
5. Включите телевизор и подождите пока в HA он поменяет состояние на "включено"
6. Снова скриншот атрибутов
7. Попробуйте поуправлять телевизором из УДЯ
8. Если из УДЯ не управляется - обновите список устройств в УДЯ и снова попробовать поуправлять из УДЯ
9. Приложите сюда скриншоты атрибутов и home-assistant.log (в каталоге где configuration.yaml)

**Comment by salex105** [comment]
Извиняюсь за задержу (работа)
Прикладываю скриншоты и логи.
![Philips_off](https://user-images.githubusercontent.com/119597350/208710093-4fbc6999-9a8f-4a23-b79c-4c029c30cf7b.jpg)
![Philips_on](https://user-images.githubusercontent.com/119597350/208710100-1acab584-fa18-44fb-992e-ff5c960879e5.jpg)
[home-assistant.log](https://github.com/dext0r/yandex_smart_home/files/10270015/home-assistant.log)
[home-assistant.log.1.log](https://github.com/dext0r/yandex_smart_home/files/10270021/home-assistant.log.1.log)

**Comment by salex105** [comment]
Также обнаружил, что из пункта Панель разработчика - Службы - Пульт ДУ: Send Command
Хорошо выполняются команды, например, переключение на 55 канал:

service: remote.send_command
data:
  command: Digit5
  num_repeats: 2
target:
  entity_id: remote.philips_tv_remote

Как бы сынтегрировать с УДЯ ?

**Comment by dext0r** [comment]
По поддержке выбора каналов для philips_js создан отдельный ишью #422, но не факт, что он в вашем случае сработает.

> Как бы сынтегрировать с УДЯ ?

Можно воспользоваться "пользовательскими умениями" (https://docs.yaha-cloud.ru/v0.6.x/advanced/capabilities/#custom-ranges). В вашем случае это будет выглядеть как-то так:
```yaml
yandex_smart_home:
  entity_config:
    media_player.philips_tv:
      custom_ranges:
        channel:
          # две следующие строчки - это костыль, текущий канал взять неоткуда
          state_entity_id: remote.philips_tv_remote
          state_attribute: features  
          set_value:
            service: script.philips_tv_send_channel
            data:
              channel: '{{ value }}'
          range:
            min: 0
            max: 999
```

`script.philips_tv_send_channel` нужно реализовать самостоятельно
