### ISSUE TITLE
В последнее время участились предупреждения 

### ISSUE THREAD

**Issue by nikrays** [dext0r/yandex_smart_home#423]
Failed to send state notification: [500] b'Internal Server Error\n'
Failed to send state notification: [401] b'Unauthorized\n'

С чем это связанно? У всех сейчас так?

**Comment by dext0r** [comment]
Проблемы на стороне УДЯ. После 22:20 (МСК) проблем не вижу. У вас продолжается?

**Comment by nikrays** [comment]
Нет, хорошо, спасибо
