### ISSUE TITLE
Привязать устройства второго дома

### ISSUE THREAD

**Issue by udavst** [dext0r/yandex_smart_home#424]
Есть 2 дома с двумя ha. привязал первый - датчики подтянулись, всё работает. Пытаюсь привязать устройства во втором доме (отдельный ha, интеграция установлена), но при выборе в умном доме алисы  + yaha, он уже видит устройства первого дома, и возможности авторизовать второй ha нет.

**Comment by dext0r** [comment]
В УДЯ к одному аккаунту можно привязать навык только один раз, и на это никак повлиять невозможно. Единственное решение - использовать прямое подключение с отдельными навыками для каждого HA.
