### ISSUE TITLE
'yandex_smart_home' not found при попытке запустить компонент на HA в контейнере

### ISSUE THREAD

**Issue by szhebet** [dext0r/yandex_smart_home#436]
Подскажите, работает ли данная интеграция с HA в контейнере (контейнерная инсталляция HA)?
При попытке подключить интеграцию yandex_smart_home на HA в контейнере получаю ошибку:

The system cannot restart because the configuration is not valid: Component error: yandex_smart_home - Integration 'yandex_smart_home' not found.

**Comment by dext0r** [comment]
Если интеграция ставилась вручную, скорее всего неправильно был распакован архив (см. [документацию](https://docs.yaha-cloud.ru/v0.6.x/install/component/#manual)). Проверить можно по наличию файлика `custom_components/yandex_smart_home/manifest.json`.
Рекомендую установить интеграцию через HACS.

**Comment by szhebet** [comment]
Спасибо!
Разобрался, все заработало
