### ISSUE TITLE
Monitoring CPU temperature

### ISSUE THREAD

**Issue by SergeKZ** [dext0r/yandex_smart_home#439]
Доброй ночи я добивил сенсор в HA для показы температуры процессора и хотел бы его пробросить в алису, я в настройках указал чтобы передавать этот сенсор яндексу но в приложении ДОМ сенсор именно мониторинга температуры CPU не отображается подскажите какие настройки необходимо сделать?

**Comment by dext0r** [comment]
Обсудили в чате (https://t.me/yandex_smart_home/49614)
