### ISSUE TITLE
Unable to get Yandex mode for "LOW_MID" for fan_speed instance of climate.konditsioner.

### ISSUE THREAD

**Issue by plesetsk** [dext0r/yandex_smart_home#440]
Home assistant 2023.3.1
Yandex smart home 0.6.2

Эта ошибка возникла в кастомной интеграции.

```
Logger: custom_components.yandex_smart_home.capability_mode
Source: custom_components/yandex_smart_home/capability_mode.py:142
Integration: Yandex Smart Home (documentation, issues)
First occurred: 01:00:02 (161 occurrences)
Last logged: 12:23:49

Unable to get Yandex mode for "LOW_MID" for fan_speed instance of climate.konditsioner. It may cause inconsistencies between Yandex and HA. Check "modes" setting for this entity
```

У кондиционера есть следующие атрибуты:

hvac_modes:
  - 'off'
  - heat
  - dry
  - cool
  - fan_only
  - heat_cool
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes:
  - LOW
  - LOW_MID
  - MID
  - MID_HIGH
  - HIGH
  - NATURE
swing_modes:
  - VerticalOff
  - VerticalTop
  - VerticalMiddleTop1
  - VerticalMiddleTop2
  - VerticalMiddleBottom2
  - VerticalMiddleBottom1
  - VerticalBottom
  - VerticalSwing
  - VerticalOff
  - HorizontalOff
  - HorizontalLeft
  - HorizontalMiddleLeft
  - HorizontalCenter
  - HorizontalMiddleRight
  - HorizontalRight
  - HorizontalLeftHalf
  - HorizontalRightHalf
  - HorizontalSwing
current_temperature: 24.5
temperature: 25
fan_mode: LOW_MID
swing_mode: VerticalSwing
swing_mode_horizontal: HorizontalSwing
swing_mode_vertical: VerticalSwing
friendly_name: Кондиционер
supported_features: 41

Предупреждение возникает начиная с момента установки компонента.

**Comment by dext0r** [comment]
Какой интеграцией добавлен кондиционер?

**Comment by plesetsk** [comment]
> Какой интеграцией добавлен кондиционер?

Извиняюсь, забыл указать

[ha-smartthinq-sensors](https://github.com/ollo69/ha-smartthinq-sensors)

**Comment by dext0r** [comment]
Если честно, у меня нет идей в какому режиму Яндекса можно автоматически отнести значение `LOW_MID` (и `MID_HIGH` тоже).

Список возможных режимов тут - https://yandex.ru/dev/dialogs/smart-home/doc/concepts/mode-instance-modes.html

**Comment by dext0r** [comment]
Выглядит хорошо, спасибо. Автоматическое связывание появится в следующей версии, а пока вы можете настроить связку вручную через entity_config: https://docs.yaha-cloud.ru/v0.6.x/config/modes/

**Comment by plesetsk** [comment]
Спасибо!

**Comment by dext0r** [comment]
Для сохранения обратной совместимости с существующими кондиционерами пришлось сделать так:
```
LOW_MID: Минимальный (min)
MID_HIGH: Максимальный (max)
```

Если вы настроили связку вручную, для вас ничего не изменится.
