### ISSUE TITLE
Aqara EU smart plug (SP-EUC01) передается в Дом яндекса как выключатель

### ISSUE THREAD

**Issue by SlyFoxeh** [dext0r/yandex_smart_home#443]
Aqara EU smart plug (SP-EUC01) передается в Дом яндекса как выключатель, при этом если добавить с розетки в интеграцию дополнительные сенсоры (Ток, напряжение), то в доме от яндекса они появляются как новые ОТДЕЛЬНЫЕ датчики. 
Пару раз оно линковалось к розетке само, но потом пропадало снова
![image](https://user-images.githubusercontent.com/448991/229111030-0f749f38-6ad0-4a9d-a06d-18b022885f14.png)

**Comment by dext0r** [comment]
https://docs.yaha-cloud.ru/v0.6.x/devices/sensor/
