### ISSUE TITLE
Нет кнопки Привязки

### ISSUE THREAD

**Issue by almirus** [dext0r/yandex_smart_home#446]
Откройте [квазар](https://yandex.ru/quasar/iot) или приложение [Дом с Алисой](https://mobile.yandex.ru/apps/smarthome)
Нажмите кнопку "+" в правом верхнем углу, выберите "Устройство умного дома"
Найдите в списке и выберите производителя "Yaha Cloud"
Нажмите кнопку "Привязать к Яндексу", откроется страница авторизации
После клика по Yaha Cloud просто перекидывает в [веб приложение](https://yandex.ru/alice/smart-home?referrer=appmetrica_tracking_id%3D532061353850968862%26ym_tracking_id%3D14365585804544507728#app) и там нет кнопки привязки, делаю с PC

![image](https://github.com/dext0r/yandex_smart_home/assets/16898685/7986dec4-9d7c-430f-a8d8-a1dcfc789f4d)

**Comment by dext0r** [comment]
Воспользуйтесь приложением "Дом с Алисой". Упоминание квазара в скором времени будет удалено из документации.
