### ISSUE TITLE
Событие при неуспешной попытке управления устройством

### ISSUE THREAD

**Issue by Blacksli** [dext0r/yandex_smart_home#447]
Добрый день. В мастер ветке было добавлено событие при успешном управлении устройством

https://github.com/dext0r/yandex_smart_home/blob/39a979ee9ae7fddffe6efca23f39a7470bbbeb9d/docs/advanced/events.md

А есть возможность добавить event при неуспешном управлении (например, устройство отвалилось)?
И возможно ли в event указывать от какой колонки поступили запросы?

**Comment by dext0r** [comment]
> А есть возможность добавить event при неуспешном управлении (например, устройство отвалилось)?

Да, переделаю, чтобы событие посылалось в любом случае, а внутри события добавлю код ответа в УДЯ.

> И возможно ли в event указывать от какой колонки поступили запросы?

Нет, УДЯ не предоставляет информацию о том, откуда была подана команда.
