### ISSUE TITLE
Использование Voice assistants -> Expose

### ISSUE THREAD

**Issue by Shulyaka** [dext0r/yandex_smart_home#449]
Добрый день!
Что насчёт идеи использования выбора устройств через нативный интерфейс (желательно с возможностью переопределить через YAML.
![image](https://github.com/dext0r/yandex_smart_home/assets/2741408/84cc975f-2695-40f9-83d1-b880bcf8c8ba)

Я бы предложил использовать этот интерфейс при выборе устройств по приоритетам между `exclude_domains`/`include domains` и `exclude_entities`/`include entities`. То есть сначала смотрим на уровне доменов, потом убираем неотмеченные как Expose в GUI, а потом добавляем или убираем на уровне entity в yaml.

**Comment by dext0r** [comment]
Это отличная идея, но есть проблема: в HA список доступных голосовых ассистентов [захардкожен](https://github.com/home-assistant/core/blob/311c321d06269da0b9c1f52abb7312ee8d4dae4f/homeassistant/components/homeassistant/exposed_entities.py#L23). Поэтому добавить свой не получится :(

**Comment by Shulyaka** [comment]
А если экспортировать то же самое, что экспортируется в conversation?

**Comment by dext0r** [comment]
> А если экспортировать то же самое, что экспортируется в conversation?

Мне кажется это не совсем правильно. Уже есть активные пользователи conversation, у которых в него передано больше объектов чем в УДЯ. В итоге это добавит больше вреда чем пользы.

Ишью оставлю открытым. Подумаю о настройке, которая будет включать такое поведение, но пока это не приоритетная задача.

**Comment by Shulyaka** [comment]
Ок, спасибо! Думаю, надо зарейзить в HA кор, чтобы добавили поддержку кастомных ассистентов.
Ишью можно закрыть когда будет удобно)

**Comment by dext0r** [comment]
Заметил одно нехорошое поведение: вновь добавленное устройство автоматически экспозится в ассистента. А это значит, что оно автоматически будет уезжать в УДЯ. А как мы знаем, удаление устройств из УДЯ - это боль.

Представьте, что вы добавили несколько лампочек в ХА -> они сразу автоматом уехали в УДЯ -> переименовали лампочки в ХА -> поменялись идшники -> новые идшники снова уехали в УДЯ.
В итоге мы будем иметь в УДЯ много дублей, которые замучаешься вычищать руками.

Так что отложим задачу до лучших времён.

Какой лично у меня текущий флоу по новым устройствам:
1. Добавляем устройство в ХА
2. Переименоваем entity_id по-красоте
3. Добавляем устройству русский алиас + комнату через гуй
4. Размечаем entity_config по вкусу при необходимости
5. И только потом выбираем в списке устройств для передачи
