### ISSUE TITLE
Теливизоры Samsung перестали появлятся в YaHA

### ISSUE THREAD

**Issue by rDaimon** [dext0r/yandex_smart_home#455]
Перевожу компоненты одного дома в другой, конфигурации сервера HA (аппаратные и программные) абсолютно аналогичны друг другу. К сожалению телевизоры Samsung не появлются в умном доме Yandex, хотя иные устройства передаются без проблем. На предыдущем сервере, связка HA-YaHA работала без проблем. Возможно обновились интеграции в HA для Samsung либо что-то в YaHA... 
Помогите разобраться с проблемой. Спасибо!

**Comment by dext0r** [comment]
Эти телевизоры точно выбраны в списке устройств для передачи? Может у них изменились ID объектов на новом сервере.

**Comment by rDaimon** [comment]
Сервис YaHA был отключен в УДЯ и подключен с новыми учетными данными. Все
устройства умного дома последовательно регистрируются на новом сервере HA,
добавляются к публикации в УДЯ, конечно у них новые ID и наименования.
Никакого копирования конфигураций не происходит. Добавлять телевизоры
пробовал в разном порядке с одним результатом. Сама интеграция в HA
работает корректно. Иные устройства (реле, диммеры и т.д.) добавляются без
проблем.
На очереди: попробовать кастомную интеграцию для телевизоров Samsung (
https://github.com/ollo69/ha-samsungtv-smart).
Полагаю, что проблема скрыта где-то в другом месте и связана с самим
процессом перехода...
Опция отладки подключения в КРЯ, которая была ранее заявлена к разработке,
как скоро будет доступна?

пн, 21 авг. 2023 г. в 08:53, Artem Sorokin ***@***.***>:

**Comment by rDaimon** [comment]
Первый телевизор:
Состояние:
on
source_list:
  - TV
  - HDMI
  - 2GIS
  - Almatel
  - Apple TV+
  - Cloudio TV
  - DS video
  - Facebook Watch
  - "Google\_Play\_Фильмы"
  - Internet
  - KION
  - MEGOGO ТВ и Кино
  - McAfee Security for TV
  - Netflix
  - NewsFrontTV
  - 'Okko: кино, сериалы, спорт, ТВ'
  - PREMIER
  - Peers.TV
  - Plex
  - Prime Video
  - Privacy Choices
  - RUTUBE
  - START Фильмы и сериалы 4К
  - Spotify - музыка и подкасты
  - Tvigle
  - Wink
  - YouTube
  - YouTube Kids
  - e-Manual
  - more.tv
  - Больше TV
  - Иви
  - ИнеткомТВ (InetcomTV)
  - 'Кинопоиск: кино и сериалы'
  - Клуб Samsung
  - МегаФон ТВ
  - Первый
  - Русская Музыка
  - СТС
  - Сериалы HD. Amediateka.
  - Яндекс
  - билайн тв
  - кинотеатр tvzavr
device_class: tv
friendly_name: Спальня, телевизор
supported_features: 20413
volume_level: 0.12
is_volume_muted: false

Второй телевизор:
Состояние:
on
source_list:
  - TV
  - HDMI
  - 2GIS
  - DS video
  - GameFly Streaming
  - KION
  - Netflix
  - 'Okko: кино, сериалы, спорт, ТВ'
  - PREMIER
  - Privacy Choices
  - START Фильмы и сериалы 4К
  - Web Browser
  - Wink
  - YouTube
  - e-Manual
  - more.tv
  - Иви
  - 'Кинопоиск: кино и сериалы'
  - Клуб Samsung
  - МегаФон ТВ
  - Русская Музыка
  - Яндекс
volume_level: 0.21
is_volume_muted: false
device_class: tv
friendly_name: Гостинная, телевизор
supported_features: 20413

пн, 21 авг. 2023 г. в 11:33, Artem Sorokin ***@***.***>:

**Comment by rDaimon** [comment]
Удалось добавить устройство ручным обновлением навыка УДЯ (нашел упоминание
об этом в документации).
Примечательно, что другие типы устройств и до и после телевизоров
обнаруживаются автоматически.
Наличие запятой в  friendly_name никак не влияет на обнаружение устройства.
Вопрос можно считать разрешенным. Спасибо!

пн, 21 авг. 2023 г. в 21:57, Dmitriy Borisov ***@***.***>:

**Comment by dext0r** [comment]
> Примечательно, что другие типы устройств и до и после телевизоров обнаруживаются автоматически.

Автоматически в УДЯ появляются только те устройства (по entity_id), которых ранее не было в УДЯ для вашей УЗ. 
Другими словами, если вы добавили в УДЯ устройство `media_player.test`, затем удалили его из списка устройства для передачи, и удалили из УДЯ - то при следующем добавлении в список устройств для передачи оно не появится автоматически в УДЯ, потребуется нажать "Обновить список устройств" вручную.
