### ISSUE TITLE
Не обновляется список устройств удя

### ISSUE THREAD

**Issue by Saprus13** [dext0r/yandex_smart_home#456]
При попытке обновления выдает ошибку "Не получилось обновить список устройств".

В журнале сервера HA ошибка:
Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/smart_home.py:68
Integration: Yandex Smart Home ([documentation](https://github.com/dmitry-k/yandex_smart_home), [issues](https://github.com/dmitry-k/yandex_smart_home/issues))
First occurred: 15:24:12 (1 occurrences)
Last logged: 15:24:12

Handler unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 37, in async_handle_message
    result = await handler(hass, data, message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 68, in async_devices
    ent_reg = await entity_registry.async_get_registry(hass)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'

**Comment by dext0r** [comment]
Обновите компонент до последней версии (0.6.3)

**Comment by Saprus13** [comment]
Компонент установлен последней версии. Видимо причина не в этом. Стоит ли удалить связанные объекты в удя? Но боюсь что потом обновить и привязать снова не смогу

**Comment by Saprus13** [comment]
![Screenshot_2](https://github.com/dext0r/yandex_smart_home/assets/99300133/43fcdc86-73d0-43dd-a731-02fb7826b6a8)

**Comment by Saprus13** [comment]
Всё заработало. Спасибо!
