### ISSUE TITLE
перестало прокидываться атмосферное давление

### ISSUE THREAD

**Issue by Crazy-Child** [dext0r/yandex_smart_home#457]
Перестало прокидываться атмосферное давление с датчика [WSDCGQ11LM]. Температура и влажность в УДЯ с него прокидывается нормально.

**Comment by dext0r** [comment]
Прикидывается как отдельное устройство или в составе другого? Пробовали обновлять список устройств УДЯ вручную?

**Comment by Crazy-Child** [comment]
Прокинуто как отдельное устройство. Раньше работало, но с 2 августа не обновлял данные. Я его удалил, заново прокинул, но УДЯ его не видет. Да, конечно обновлял список устройств. Соответсвенно показания температуры и влажности с данного датчика прекрасно прокинулись как отдельные датчики. В ХА непосредственно все работает, данные обновляются.

**Comment by MartynIden** [comment]
аналогичная проблема примерно с того же времени, попробовал перепрокинуть датчики - температура и влажность появляются в УДЯ а давление - нет.

**Comment by dext0r** [comment]
> 

1. Всё таки убедитесь, что проблемный датчик есть в списке устройств для передачи. Возможно у него поменялся entity_id.
2. Покажите атрибуты и состояние проблемного датчика из Панель разработчика -> Состояния.
3. Покажите целиком yaml конфиг для yandex_smart_home.

**Comment by Crazy-Child** [comment]
![image](https://github.com/dext0r/yandex_smart_home/assets/102763254/efb91e54-34f2-49ad-8201-2f8a62f12f28)
![image](https://github.com/dext0r/yandex_smart_home/assets/102763254/cbbae252-0c84-4ee8-abc6-66aa7580caf0)

**Comment by Crazy-Child** [comment]
"Покажите целиком yaml конфиг для yandex_smart_home" - не знаю как это сделать. он установлен через HACS и все датчики прокинуты через браузерную версию, как на картинках выше.

**Comment by dext0r** [comment]
Проблема Понятна. В ближайшее время будет выпущено исправление.

Причина: появление нового device_class для атмосферного давления.

**Comment by dext0r** [comment]
Исправлено в версии 0.6.4
