### ISSUE TITLE
Не могу добавить второй аккаунт яндекс

### ISSUE THREAD

**Issue by dprovoker** [dext0r/yandex_smart_home#463]
Пытаюсь привязать вторую колонку настроенную на другой аккаунт используя этот мануал: https://docs.yaha-cloud.ru/v0.6.x/advanced/clone/

Интеграцию клонировал, однако не появляется окно настройки, где указаны коды для подключения

![2023-10-07_02-21-41](https://github.com/dext0r/yandex_smart_home/assets/85135818/57899c08-9a2d-44cb-ae18-bea05dfd2f9f)

**Comment by dext0r** [comment]
Попробуйте обновить страницу. Убедитесь, что был скопирован каталог custom_components/yandex_smart_home целиком (включая подкаталоги).
