### ISSUE TITLE
Diyruz_flower передает освещенность вместо влажности

### ISSUE THREAD

**Issue by Jon811** [dext0r/yandex_smart_home#474]
Имеется:
[Flower sensor](http://modkam.ru/?p=1700) (DIYRuZ_Flower)
DIYRuZ через z2m
Версия программного обеспечения: 22/04/2021 11:13
Яндекс напрямую со своим навыком.
При попытке передать в яндекс данные влажности передаются данные с датчика освещенности в люксах, причем с именем датчика влажности почвы. Если передавать датчик освещения, передается имя датчика освещённости с его же данными. Перепривязка датчика в НА и Яндексе не помогает

**Comment by dext0r** [comment]
Покажите атрибуты переданного в УДЯ объекта/ов из Панель разработчика - Состояния.

**Comment by Jon811** [comment]
> Покажите атрибуты переданного в УДЯ объекта/ов из Панель разработчика - Состояния.
![image](https://github.com/dext0r/yandex_smart_home/assets/58070934/ebde207d-b716-4c15-8827-9dbca7762c0c)

![image](https://github.com/dext0r/yandex_smart_home/assets/58070934/4a3d0bfc-9caf-4591-a592-1b31ad1166f3)

**Comment by dext0r** [comment]
Отключите в zigbee2mqtt функцию `legacy_entity_attributes`: https://www.zigbee2mqtt.io/guide/configuration/homeassistant.html#advanced-configuration

**Comment by Jon811** [comment]
> Отключите в zigbee2mqtt функцию `legacy_entity_attributes`: https://www.zigbee2mqtt.io/guide/configuration/homeassistant.html#advanced-configuration

Сделал, перезагрузил всё что можно. Поудалял везде этот датчик. Теперь добавляю его в интеграции в объекты для передачи, а в Яндексе оно не появляется при обновлении устройств.

**Comment by dext0r** [comment]
> ![image](https://user-images.githubusercontent.com/58070934/278878573-1e56c141-321f-4af4-a3d7-19dcbef07d58.png)

В таком виде датчик автоматически не будет обнаружен, так как недостаточно информации, чтобы достоверно определить его тип (отсутствует device_class).

device_class для влажности почвы не указывается в zigbee2mqtt - https://github.com/Koenkk/zigbee2mqtt/blob/51f15bd306db1249e02b0d4fd433d06173ac0e04/lib/extension/homeassistant.ts#L733 

В данном случае придётся задействовать датчик через properties, например так:
```yaml
yandex_smart_home:
  entity_config:
   sensor.dtgorshok_soil_moisture:
     properties:
       - type: temperature
         entity: sensor.dtgorshok_soil_moisture
```

**Comment by Jon811** [comment]
Да, так получилось, только 
- type: humidity
указал

**Comment by dext0r** [comment]
> Да, так получилось, только
> 
> * type: humidity
>   указал

Конечно же humidity, я опечатался 😞

**Comment by dext0r** [comment]
Отправил pull request в z2m для добавления правильного device class: https://github.com/Koenkk/zigbee2mqtt/pull/19486

Дополнительно требуется добавить обработку `device_class: moisture` в компоненте.

**Comment by dext0r** [comment]
Автоматическое обнаружение датчика влажности почвы заработает начиная с z2m >= 1.33.2 и yandex_smart_home >= 1.0.0
