### ISSUE TITLE
Предупреждение: Failed to send state notification: [401] b'Unauthorized\n' при подключении через YaHa Cloud

### ISSUE THREAD

**Issue by x-iLex-x** [dext0r/yandex_smart_home#481]
Стали сыпаться предупреждения в лог.
Подключение к УДЯ через YaHa Cloud.

```
Logger: custom_components.yandex_smart_home.notifier
Source: custom_components/yandex_smart_home/notifier.py:163
Integration: Yandex Smart Home ([documentation](https://docs.yaha-cloud.ru/v0.6.x/), [issues](https://github.com/dext0r/yandex_smart_home/issues))
First occurred: 14:40:16 (1 occurrences)
Last logged: 14:40:16

Failed to send state notification: [401] b'Unauthorized\n'
```

**Comment by dext0r** [comment]
Такие ответы возвращаются от УДЯ. Проблема периодически наблюдается с 3 ноября, остаётся только ждать. На управление устройств это не влияет.

Ишью пока оставлю открытым.

**Comment by x-iLex-x** [comment]
> Такие ответы возвращаются от УДЯ. Проблема периодически наблюдается с 3 ноября, остаётся только ждать. На управление устройств это не влияет.
> 
> Ишью пока оставлю открытым.

Да, и дополню - статус устройств УДЯ тоже получает без проблем. Спасибо :)

**Comment by LordXaosa** [comment]
На прямом подключении тоже наблюдается (если это важно)

**Comment by dext0r** [comment]
После 16.11 12:00 ситуация стабилизировалась. Вала Unauthorized на облаке не вижу. Ишью закрываю.
