### ISSUE TITLE
Произошла ошибка Произошла внутренняя ошибка. Cannot-set-properties-of-undefined-(setting-'app')-1701703126613

### ISSUE THREAD

**Issue by Pestkov** [dext0r/yandex_smart_home#488]
![Screenshot_2023-12-04-20-47-30-457_com yandex iot](https://github.com/dext0r/yandex_smart_home/assets/50014906/91165e8a-c9e3-42f4-bfca-dc192a247bb0)
Ошибка после авторизации через навык yaha.cloud умного дома яндекс

**Comment by aries-soft** [comment]
![photo_2023-12-04_18-35-28](https://github.com/dext0r/yandex_smart_home/assets/1010139/9fd10d89-45e8-415b-8d41-f60f6fca4a96)

**Comment by dext0r** [comment]
Что то на стороне УДЯ, по приватным навыкам тоже самое. В чате помог переход на мобильную сеть.

**Comment by marboroman** [comment]
Worked again
