### ISSUE TITLE
Нет связи с устройством

### ISSUE THREAD

**Issue by Ivanini70** [dext0r/yandex_smart_home#490]
Устройство (button, открывающий ворота паркинга. из интеграции ПИК), переданное из HA в УДЯ как через YAHA, так и напрямую, не работает ("Нет связи с устройством"). Другие устройства (других типов и интеграций) работают без проблем.
Возможно, что это связано с закрепленным issue?
Точно не следил, но неделю назал четыре шлагбаума работали, но на этой неделе добавил ещё два - теперь не работает ни один! Пытаюсь завести хоть один.
В чате поддержки Яндекс Станции сказали, что "Полагаем, ситуация вызвана на стороне навыка Yaha Cloud", поэтому перешёл на прямое подключение. Но ничего не поменялось.
Диагностика (часть про устройство):
{
"type": "devices.capabilities.on_off",
"retrievable": false,
"reportable": false
}
"state": {
"id": "button.kd_01_012_unlocker",
"error_code": "DEVICE_UNREACHABLE"
}
}
"entity_config": {
"button.kd_01_012_unlocker": {
"type": "devices.types.openable"
},
Из HA:
id: 48413
location: *** улица, д.
type: iot_relay
original_name: Выезд. Подземная часть рампы. 
custom_name: null
is_favorite: false
is_hidden: false
icon: mdi:transfer-up
friendly_name: Из паркинга

Дополню:
Статус "DEVICE_UNREACHABLE" получается не в "if self.unavailable", видмо в "if not capabilities and not properties". При нажатии на "серые" кнопки в приложении и Квазаре всё срабатывает, т.е. на самом деле связь работает, но голосом Алиса не управляет

**Comment by dext0r** [comment]
> Возможно, что это связано с закрепленным issue?

Нет

> Точно не следил, но неделю назал четыре шлагбаума работали, но на этой неделе добавил ещё два - теперь не работает ни один! Пытаюсь завести хоть один.

Покажите атрибуты и состояние проблемных объектов из Панель разработчика - Состояния (лучше скриншотом). Какая версия компонента установлена? (можно посмотреть в custom_components/yandex_smart_home/manifest.json)

**Comment by Ivanini70** [comment]
1)
![image](https://github.com/dext0r/yandex_smart_home/assets/139058831/6259f0ee-2144-41b9-9240-dc660462635d)
2)
"version": "1.0.0.dev1"

**Comment by dext0r** [comment]
Проблему подтверждаю, она только в нестабильном мастере. Можно пока откатиться на 0.6.6, там её нет.

**Comment by dkuznets** [comment]
Непонятная проблема.Прокинул датчики из безумного дома в УДЯ. Устройства появились, но всех пишет "нет связи с устройством". Все датчики описаны в HA однотипно     
- name: "Температура в гостиной" 
      unique_id: "ESP_80E092_TEMP1" 
      device_class: temperature 
      state_topic: "/ESP_80E092/BME280/Temperature" 
      unit_of_measurement: "°С" 
      icon: mdi:home-thermometer 
      availability: 
        - topic: "/ESP_80E092/status/LWT" 
      payload_available: "online" 
      payload_not_available: "offline"

Выключатели нормально управляются с телефона, правда не понимаю, как их на колонку завязать.
