### ISSUE TITLE
Не удалось загрузить мастер настройки: {"message":"Handler does not support user"}

### ISSUE THREAD

**Issue by dangerdanik** [dext0r/yandex_smart_home#492]
Подскажите, пожалуйста, в чем проблема? Хотел добавить устройство в УДЯ. При попытки открыть настройки интеграции - Не удалось загрузить мастер настройки: {"message":"Handler does not support user"} 
![Screenshot_2](https://github.com/dext0r/yandex_smart_home/assets/41535168/8f6121b8-dc27-4bc2-8c84-edb0e9e8bd9b)

**Comment by dext0r** [comment]
Обновите компонент до последней версии или установите поверх повторно через HACS.

**Comment by dangerdanik** [comment]
Спасибо за ответ. Подскажите, если повторно установлю через HACS, не слетят те устройства что уже добавлены в УДЯ? В HACS как установленного компонент почему то не нашел.

**Comment by dangerdanik** [comment]
Понял! Спасибо!
