### ISSUE TITLE
Home Assistant Core 2024.1 заваливает лог ошибками

### ISSUE THREAD

**Issue by Sheredeka** [dext0r/yandex_smart_home#496]
[home-assistant_2024-01-04T13-33-02.163Z.log](https://github.com/dext0r/yandex_smart_home/files/13830352/home-assistant_2024-01-04T13-33-02.163Z.log)

Core 2024.1.0
Supervisor 2023.12.0
Operating System 11.2
Пользовательский интерфейс 20240103.3

Интеграция работает, но в логе масса предупреждений.
Лог прицеплен.

**Comment by dext0r** [comment]
Установите версию 0.6.8
https://github.com/dext0r/yandex_smart_home/releases/tag/v0.6.8
