### ISSUE TITLE
Some deprecated features in HA 2024.1

### ISSUE THREAD

**Issue by algar42** [dext0r/yandex_smart_home#497]
Начиная с версии HA 2024.1 в логе появились следующие предупреждения:

DEVICE_CLASS_VOLTAGE was used from yandex_smart_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.VOLTAGE instead
ELECTRIC_CURRENT_MILLIAMPERE was used from yandex_smart_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.MILLIAMPERE instead
ENERGY_WATT_HOUR was used from yandex_smart_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead
TEMP_CELSIUS was used from yandex_smart_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead
VOLUME_LITERS was used from yandex_smart_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.LITERS instead
HVAC_MODE_OFF was used from yandex_smart_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead

**Comment by dext0r** [comment]
Обновите компонент до версии 0.6.8
https://github.com/dext0r/yandex_smart_home/releases/tag/v0.6.8
