### ISSUE TITLE
Чайник на домене climate

### ISSUE THREAD

**Issue by panfmik** [dext0r/yandex_smart_home#502]
Подключил чайник redmond, в ha он отдается в домене climate, управление голосом работает норм, но в УДЯ чайник все время отображается включеным.

![image](https://github.com/dext0r/yandex_smart_home/assets/76124235/54745e8b-d9ef-476d-ad56-9e740c107791)

ошибка в ha

![image](https://github.com/dext0r/yandex_smart_home/assets/76124235/15e24cd0-1b83-4a2f-9a28-1f84f82549b0)

![image](https://github.com/dext0r/yandex_smart_home/assets/76124235/28844237-9da0-4582-8ab6-9cf7b3062423)

**Comment by dext0r** [comment]
Какой интеграций добавлен чайник?
Покажите не только атрибуты, но и состояние `climate.r4s01_kettle_temp` из панели разработчика.
Выполнялись какие либо настройки для этого чайника через entity_config? Если да - покажите.

**Comment by panfmik** [comment]
[ESP32-R4sGate-for-Redmond](https://github.com/alutov/ESP32-R4sGate-for-Redmond)

чайник выключен
![image](https://github.com/dext0r/yandex_smart_home/assets/76124235/98fa9b10-09ce-4b51-8fd5-b266061c90ef)

чайник включен в нагрев
![image](https://github.com/dext0r/yandex_smart_home/assets/76124235/dfff4eea-1843-464b-8182-1a2d2f9a6d84)

чайник включен в поддержание температуры
![image](https://github.com/dext0r/yandex_smart_home/assets/76124235/ee15b757-26e3-4fb3-a2c1-10dd2df6bbfa)


    climate.r4s01_kettle_temp:
      name: Чайник
      room: Кухня
      type: devices.types.cooking.kettle
      custom_toggles:
        backlight:
          state_entity_id: switch.r4s01_kettle_backlight
          turn_on:
            service: switch.turn_on
            entity_id: switch.r4s01_kettle_backlight
          turn_off:
            service: switch.turn_off
            entity_id: switch.r4s01_kettle_backlight
        mute:
          state_entity_id: switch.r4s01_kettle_beep
          turn_on:
            service: switch.turn_on
            entity_id: switch.r4s01_kettle_beep
          turn_off:
            service: switch.turn_off
            entity_id: switch.r4s01_kettle_beep
      custom_ranges:
        temperature:
          state_entity_id: climate.r4s01_kettle_temp
          set_value:
            service: climate.set_temperature
            target:
              entity_id: climate.r4s01_kettle_temp
            data:
              temperature: '{{ value }}'
          range:
            min: 0
            max: 100
            precision: 5
      properties:
        - type: temperature
          entity: climate.r4s01_kettle_temp
          attribute: current_temperature
        - type: electricity_meter
          entity: sensor.r4s01_kettle_energy

**Comment by dext0r** [comment]
Уберите custom_ranges->temperature из entity_config. Это не нужно, так как регулировка температуры базовая функция термостата и работает автоматически. Возможно это создаёт проблемы.

Что касается неверного статуса: у вас прямое подключение? Настроен этот механизм? - https://docs.yaha-cloud.ru/master/advanced/direct-connection/#notifier

**Comment by panfmik** [comment]
подключение облачное

`Уберите custom_ranges->temperature из entity_config.` - хм, помогло
