### ISSUE TITLE
Доработки документации (общая задача)

### ISSUE THREAD

**Issue by dext0r** [dext0r/yandex_smart_home#504]
- [x] Уточнить, что HACS нужно добавить после установки + правки под HACS 2
- [x] [Очепятка](https://github.com/dext0r/yandex_smart_home/blob/4e19e722dd2654005b2aa605a431892da7268bc5/docs/devices/light.md?plain=1#L98)
- [x] Добавление интеграции: +компонент должен быть установлен
- [x] Замена service -> action
- [x] Несколько HA в один УДЯ (+перефразировать про Облачное Плюс, +добавить на install/integration)
- [x] Актуализировать поля при создании диалога УДЯ
- [x] Обновить неактуальные скриншоты
- [x] Удалить фиче-сноски "Начиная с версии"
- [x] Переустановка компонента через HACS (повторное скачивание поверх)

**Comment by udavst** [comment]
Несколько интеграций с разными фильтрами
В документации: 
"В yandex_smart_home2/const.py измените переменную CONFIG_ENTRY_TITLE на Yandex Smart Home 2"
Нет такой строки в const.py, в итоге в HA 2 интеграции под одним именем, чужую колонку привязать не получается.
