### ISSUE TITLE
hass.agent

### ISSUE THREAD

**Issue by ops244** [dext0r/yandex_smart_home#515]
привет, после последнего обновления не работает команда "выключи компьютер" через hass.agent
https://github.com/hass-agent/HASS.Agent
не работает только голосом, при этом в самом home assistant работает и в приложении умный дом яндекса вручную работает

**Comment by dext0r** [comment]
> не работает только голосом

Что говорит Алиса? И какое название устройство имеет в УДЯ?

**Comment by ops244** [comment]
делает вид, что выполнила команду (звук издает), названия разные (не один комп)

**Comment by aseries** [comment]
У меня похожая ерунда с одной шторой. Требует обязательно сказать комнату.

чт, 15 февр. 2024 г., 17:43 ops244 ***@***.***>:

**Comment by ops244** [comment]
не, тоже не выключает с комнатой, да она вчера выключала...

**Comment by dext0r** [comment]
> У меня похожая ерунда с одной шторой. Требует обязательно сказать комнату.

Компонент не распознаёт запросы колонкам, этим занимается УДЯ.

**Comment by ops244** [comment]
так в удя все работает, нажимаешь, он выключается...

**Comment by dext0r** [comment]
> "version": "0.6.9"

В этой версии было изменено поведение скриптов (script) и кнопок (button/input_button). Теперь они реагируют только команду включения. Это изменение было сделано чтобы решить эту ситуацию - https://t.me/yandex_smart_home/78045.

Из интерфейса выключение работает, потому что при нажатии посылается команда "включить устройство".

Вижу несколько решений этой проблемы:
1. Сделать сценарий с фразой "Выключи компьютер", действие "Компьютер - включится". Фразы в сценариях всегда приоритетны
2. Сделать в HA [виртуальный](https://www.home-assistant.io/integrations/switch.template/) выключатель и отдавать в УДЯ его. Может быть такой выключатель можно сделать прямо в Hass.Agent, не знаю что именно он умеет. Идеологически более правильный вариант, так как компьютер можно будет ещё и включать и видеть его актуальное состояние в УДЯ.
3. Назвать в УДЯ устройство "Выключение компьютера" и запускать командой "Алиса, запусти выключение компьютера" (но это выглядит костылём)

**Comment by ops244** [comment]
дело как раз в том, что не у всех wake on lan работает на компьютерах (включение), а вот выключение у всех... состояние мне нужно...

**Comment by ops244** [comment]
ладно, можно закрыть, сделал через выключатель, если кому интересно вот: https://github.com/karpach/remote-shutdown-pc
