### ISSUE TITLE
input_number из helpers

### ISSUE THREAD

**Issue by sunshad0w** [dext0r/yandex_smart_home#519]
input_number. их можно добавить в настройки интеграции но в аккаунте умного дома как устройства они не появляются даже после обновления списка устройств от Yaha Cloud

**Comment by dext0r** [comment]
input_number можно использовать в пользовательских умениях: https://docs.yaha-cloud.ru/v0.6.x/advanced/capabilities/
Передавать их как устройства в планах нет.
