### ISSUE TITLE
message":"Handler does not support user"

### ISSUE THREAD

**Issue by Sergey8100** [dext0r/yandex_smart_home#521]
Ошибка возникает при клике на "Настроить" в интеграции. Перезагрузка не помогает. При полном удалении настроек и повторной конфигурации настройка работает первый запуск, потом снова та же ошибка.

**Comment by dext0r** [comment]
Обновитесь до последний версии. Если HACS не предлагает обновление - установите компонент повторно (без удаления, просто поверх).

**Comment by Sergey8100** [comment]
Это работает, спасибо!
