### ISSUE TITLE
Проблема с установкой режима кондиционера из сценария

### ISSUE THREAD

**Issue by bolt41** [dext0r/yandex_smart_home#526]
Кондиционер управляется через KNX. Наблюдается странная проблема: при управлении кондиционером в "ручном режиме" из ЯД - режимы "Охлаждение", "Авто" - переключаются без проблем. Когда создаешь сценарий в УД и указываешь в нем "Установить режим охлаждение/нагрев" - то устанавливается всегда режим "Авто". В чем может быть проблема?

**Comment by dext0r** [comment]
Скорее всего в сценарии в УДЯ добавлено действие "Кондиционер: включится". Его нужно убрать, оставив только действие по установке режима.

О том как работает включение кондиционера подробно описано в документации - https://docs.yaha-cloud.ru/v0.6.x/devices/climate/
