### ISSUE TITLE
По всей видимости не передается идентификатор HA или географическое расположение

### ISSUE THREAD

**Issue by pastukhov** [dext0r/yandex_smart_home#528]
Добрый день! Столкнулся с такой проблемой. 
У меня 2 инсталляции HA в двух домах. В обеих есть помещение "Спальня" и в обеих спальнях стоит по Алисе.
Когда я нахожусть в спальне и говорю "Алиса, включи свет", свет включается в обеих спальнях в обоих домах.
Версия интеграции везде v0.6.11
Как это исправить?

**Comment by dext0r** [comment]
Добрый день.
Это раньше работало и сейчас сломалось? Или так было всегда?
В целом компонент к этой проблема мало отношения имеет, он только выполняет команды, которые приходят от УДЯ. Какие устройства включить при голосовой команде определяет сам Яндекс.

**Comment by pastukhov** [comment]
Раньше не сталкивался с таким

**Comment by dext0r** [comment]
Попробовал у себя сделать несколько домов с комнатой "Тест", в каждую добавил по светильнику и колонке. Воспроизвести проблему не удалось. Думаю стоит обращаться в техподдержку Яндекса.
