### ISSUE TITLE
глюк интерфейса при удалении устройств

### ISSUE THREAD

**Issue by AAfetisov** [dext0r/yandex_smart_home#532]
Когда удаляешь устройство из списка, то все устройства ниже удаленного вместо своих имен отображаются как entity id

![image](https://github.com/dext0r/yandex_smart_home/assets/1430709/2e8fc7fa-bc62-49a3-8e65-02a6b0c9d5eb)

**Comment by dext0r** [comment]
Компонент использует встроенный в HA контрол для выбора объектов (EntitySelector). Аналогичное поведение вы можете наблюдать при попытке отредактировать любой вспомогательный элемент, например Группу сенсоров.
Задачу закрываю, так как это не проблема компонента. По ней лучше писать сюда - https://github.com/home-assistant/frontend


https://github.com/dext0r/yandex_smart_home/assets/3103856/ce5058f3-1d87-47c2-b681-5c32e8fb2d6c
