### ISSUE TITLE
Интеграция не работает

### ISSUE THREAD

**Issue by RusI4n** [dext0r/yandex_smart_home#535]
Не помню с какой версии HA (но уже в 2024 году) перестала работать интеграция Yandex Smart Home, уже работавшие устройства больше не отвечали, сама интеграция в HA устанавливается, но устройства в "Умный дом" при начальной настройке не переносятся, а при нажатии "настроить" в самой интеграции выдаёт ошибку:
Ошибка
Не удалось загрузить мастер настройки: {"message":"Handler OptionsFlowManager doesn't support step menu"}

**Comment by dext0r** [comment]
Обновите компонент или скачайте повторно. Интеграцию удалять не нужно.

**Comment by RusI4n** [comment]
Спасибо, вроде заработало. Обновлений никаких не выскакивало, но на
странице компонента была кнопка "скачать".
А автоматического обновления у компонента нет?
