### ISSUE TITLE
дроби в уставке для кондиционера

### ISSUE THREAD

**Issue by klim123123** [dext0r/yandex_smart_home#537]
Алиса ни в какую не хочет устанавливать и говорить дробные числа когда пытаешься установить кондиционеру целевую температуру. Связался с поддержкой Яндекс Диалогов, они сказали: Чтобы Алиса понимала десятичные дроби, на стороне разработчика навыка нужно настроить параметр precision. Подробнее про это рассказали в нашей [Документации](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/range-instance.html?lang=ru#range-instance__temperature).
Как передать precision в yandex_smart_home не нашел.

**Comment by dext0r** [comment]
Видимо техподдержка неправильно поняла вопрос. Алиса никогда не позволяла устанавливать дробные значения голосом и озвучивать их. Дробные значения можно выбирать только через приложение. Через приложение Дом с Алисой они выбираются?

**Comment by klim123123** [comment]
Да, через приложение Дом с Алисой выбирается, устанавливает без проблем. Голосом никак вообще. Напиши тогда в поддержку еще.
Еще вопрос по кондиционерам. Я говорю Алисе, включи кондиционер и она включает его всегда в тепло. Не важно какой режим стоял ранее. Есть какой-то параметр для режима по дефолту? Попробовал три разных кондиционера.

**Comment by dext0r** [comment]
> Еще вопрос по кондиционерам. Я говорю Алисе, включи кондиционер и она включает его всегда в тепло. Не важно какой режим стоял ранее. Есть какой-то параметр для режима по дефолту? Попробовал три разных кондиционера.

https://docs.yaha-cloud.ru/v0.6.x/devices/climate/
