### ISSUE TITLE
Несколько датчиков одного типа в одном устройстве

### ISSUE THREAD

**Issue by booroondook-eng** [dext0r/yandex_smart_home#539]
Да, в основной документации написано, что так сделать нельзя, но тем не менее - очень хочется.
Пример - есть бассейн с проточным подогревателем (печка на дровах). Вода из бассейна подается в подогреватель, а затем возвращается в бассейн.
При этом необходимо контролировать:
1. Температуру воды на входе в подогреватель;
2. Температуру воды на выходе из подогревателя;
3. Температуру корпуса самой печки;
4. Состояние работы циркуляционного насоса:
   4.1. Состояние включения;
   4.2. Напряжение питания;
   4.3. Ток;
   4.4. Потребляемая мощность.
По отдельности все это работает, но хотелось бы объединить в одно устройство.

**Comment by dext0r** [comment]
> Да, в основной документации написано, что так сделать нельзя, но тем не менее - очень хочется.

Всем хочется :) Но это ограничение УДЯ и с этим ничего не сделать. Единственный вариант - разбивать на несколько устройств. 

И в целом не совсем понятно, зачем это тащить в УДЯ, если в HA можно сделать гибкие дашборды с графиками и нужными показаниями.

**Comment by booroondook-eng** [comment]
> 
> И в целом не совсем понятно, зачем это тащить в УДЯ, если в HA можно сделать гибкие дашборды с графиками и нужными показаниями.

Ну... Как бы вам сказать. Мне лично гораздо удобнее спросить находящуюся в двух метрах от меня Яндекс-колонку "Алиса, что с бассейном?", чем бежать в дом, подниматься на второй этаж, запускать компьютер, открывать браузер и проверять датчики в Home Assistant'е. А вариант с судорожным поиском на смартфоне нужной иконки, чтобы запустить клиента HA, тоже не отличается удобством.
