### ISSUE TITLE
Сущность Кран

### ISSUE THREAD

**Issue by Kirorus** [dext0r/yandex_smart_home#544]
В HA есть домен valve
В УДЯ есть devices.types.openable.valve (https://yandex.ru/dev/dialogs/smart-home/doc/ru/concepts/device-type-openable-valve)

Очень прошу добавить в Интеграцию краны! Заранее спасибо

**Comment by Sergmasharov** [comment]
еще нет сущности devices.types.light.strip Светодиодной ленты
пересмотрите пожалуйста

**Comment by dext0r** [comment]
> еще нет сущности devices.types.light.strip Светодиодной ленты

https://github.com/dext0r/yandex_smart_home/releases/tag/v0.6.13

**Comment by dext0r** [comment]
> Очень прошу добавить в Интеграцию краны! Заранее спасибо

Спасибо за пулл реквест, краны доступны в 0.6.15 (и в мастере)
