### ISSUE TITLE
Не работает режим Рассвет/закат для устройств Philips hue 

### ISSUE THREAD

**Issue by pbo23** [dext0r/yandex_smart_home#551]
Недавно Яндекс добавил возможность эффектов рассвет и закат, но они работают корректно у меня только с лампочками Яндекса 
Светодиодные ленты и лампочки от Philips hue, которые прокинуты в УДЯ через yaha cloud почему то не хотят работать , то есть у них не происходит градиентного изменения цвета и яркости.
Когда включается закат или рассвет, то например для рассвета устанавливается теплый цвет на 3% яркости и все, на этом оно останавливается и дальше изменений не происходит с яркостью

**Comment by pastukhov** [comment]
Поставьте себе https://github.com/basnijholt/adaptive-lighting
Работает у меня с любым светом, умеющим менять яркость/температуру

**Comment by pbo23** [comment]
> Поставьте себе https://github.com/basnijholt/adaptive-lighting Работает с любым светом, умеющим менять яркость/температуру

Спасибо 
Действительно очень удобно
