### ISSUE TITLE
Некорректный статус устройств после перезапуска Home Assistant

### ISSUE THREAD

**Issue by codinv** [dext0r/yandex_smart_home#553]
После перезапуска Home Assistant (установлен в docker) многие устройства меняют свой статус в УДЯ на "включено"
Данная проблема наблюдается на всех Zigbee выключателях и умных реле, а так же на некоторых умных розетках
К примеру выключатели Aqara QBKG38LM, Tuya TS0002, реле Tuya WHD02
Вероятно это связано с тем, что после перезапуска HA актуальный статус устройств появляется не сразу, а в течении примерно минуты. При этом, последующий ручной перезапуск yandex_smart_home не исправляет ситуацию с устройствами в УДЯ
Нужно как то сделать отложенную повторную отправку состояния всех устройств в УДЯ, после старта интеграции yandex_smart_home

**Comment by codinv** [comment]
![20241016-104050 420](https://github.com/user-attachments/assets/d4655a34-60b4-411a-a1df-dab971ebd00a)

**Comment by dext0r** [comment]
> Вероятно это связано с тем, что после перезапуска HA актуальный статус устройств появляется не сразу, а в течении примерно минуты. 

Это ненормальное поведение, HA должен запоминать последний статус устройств и после перезапуска использовать его. 
Сейчас компонент отправляет состояния устройств через 15 секунд после **полной** загрузки HA или через 5 секунд после перезапуска интеграции.
У вас прямое или облачное подключение? Если прямо - настроен ли нотификатор? (https://docs.yaha-cloud.ru/v0.6.x/advanced/direct-connection/#notifier)

**Comment by codinv** [comment]
> Это ненормальное поведение, HA должен запоминать последний статус устройств и после перезапуска использовать его. Сейчас компонент отправляет состояния устройств через 15 секунд после **полной** загрузки HA или через 5 секунд после перезапуска интеграции. У вас прямое или облачное подключение? Если прямо - настроен ли нотификатор? (https://docs.yaha-cloud.ru/v0.6.x/advanced/direct-connection/#notifier)

Подключение настроено через облако. 
Вероятно 15ти секунд не хватает до полной инициализации и загрузки homeassistant + zigbee2mqtt + eclipse-mosquitto
Вот сегодня ночью автоматически снова обновился homeassistant и снова сутра все выключатели в состоянии включено.
Я обращал внимание, что после ручной перезагрузки какое то время все выключатели отображаются в HA не как обычно переключателем, а двумя молниями, т.е. в этот момент видимо и происходит ожидание данных от z2m, и только спустя секунд 30-40 они становятся уже в том состоянии, которое было до перзагрузки.

Было бы неплохо отправлять повторный статус именно после того как все будет до конца загружено, если можно отловить данный момент, ну или сделать повторную отправку через более продолжительное время, скажем 3 минуты, что бы наверняка..

**Comment by dext0r** [comment]
> ожидание данных от z2m

А в z2m внутри устройства на вкладке Настройки стоит галка Retain?

**Comment by codinv** [comment]
> А в z2m внутри устройства на вкладке Настройки стоит галка Retain?

Все настройки по умолчанию, ни чего дополнительно ни на одном устройстве не включалось. 
По дефолту данная галка ни где не стоит. 
То есть устройство только подключается через z2m, переименовывается сразу и все, больше ни чего не делается, все дальнейшее управление через HA.

**Comment by dext0r** [comment]
> По дефолту данная галка ни где не стоит.

Поставьте эта галку и проблема уйдет (после того, как устройства однажды отправят свой статус)

**Comment by dext0r** [comment]
> скажем создать автоматизацию, что бы после перезагрузки HA через несколько минут отправлялся статус всех, либо выбранных устройств..

Можно отправить статус всех устройств через перегрузку интеграции (сервис `yandex_smart_home.reload`). Но в реальной жизни это не нужно практически никогда.

> Столкнулся сейчас еще с тем, что вот например прокинутый пылесос, прокинутый датчик открытия двери и еще некоторые устройства, если больше чем сутки не пользуешься, стали падать в ошибку в УДЯ что давно нет данных от устройства, необходимо их проверить...

Проблема известная, планируется решение в следующих версиях (#500)

**Comment by codinv** [comment]
> Можно отправить статус всех устройств через перегрузку интеграции (сервис `yandex_smart_home.reload`). Но в реальной жизни это не нужно практически никогда.

пробовал так делать через автоматизацию в планировщике, но это не работает, т.е. некорректный статус как отображался, так и продолжал отображаться в HA ..

**Comment by dext0r** [comment]
> > Можно отправить статус всех устройств через перегрузку интеграции (сервис `yandex_smart_home.reload`). Но в реальной жизни это не нужно практически никогда.
> 
> пробовал так делать через автоматизацию в планировщике, но это не работает, т.е. некорректный статус как отображался, так и продолжал отображаться в HA ..

Нужен подробный лог работы компонента, для этого:
* Перезагрузите HA
* Включите отладку интеграции (Настройка - Устройства и службы - Интеграции - Yandex Smart Home - Начать отладку)
* Вызовите сервис `yandex_smart_home.reload` через панель разработчика или вашу автоматизацию
* Подождите 30 секунд
* Завершите отладку
* Полученный лог приложите сюда
