### ISSUE TITLE
Устройства из HA в Яндекс добавляются по частям.

### ISSUE THREAD

**Issue by mikhailfedotov** [dext0r/yandex_smart_home#556]
Раньше устройства добавлялись целиком.
Сейчас добавляются по частям.
К примеру датчик Aqara WSDCGQ11LM приходится добавлять в Яндекс не одним устройством а добавлять по частям:
- Температура
- Влажность
- Атмосферное давление
- Батарея

В умном доме яндекса отображается вместо одного 4 устройства.

**Comment by dext0r** [comment]
https://docs.yaha-cloud.ru/v0.6.x/devices/sensor/
